/*Defines the navigation bar to switch between main function of the website*/

document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("    <meta name=\"keywords\" content=\"\" />");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/head_style.css\" type=\"text/css\" media=\"all\" />");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/font-awesome.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/lightbox.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\">");
document.writeln("    <link href=\"https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext\" rel=\"stylesheet\">");
document.writeln("    <link href=\"https://fonts.googleapis.com/css?family=Lobster&amp;subset=cyrillic,latin-ext,vietnamese\" rel=\"stylesheet\">");
document.writeln("    <link href=\"https://fonts.googleapis.com/css?family=Kanit:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,thai,vietnamese\" rel=\"stylesheet\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"Main-agile\">");
document.writeln("    <div class=\"header\">");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"col-md-8 w3l_header_left\">");
document.writeln("               <ul>");
document.writeln("                    <li>Tel: 13 6352</li>");
document.writeln("                    <li>Email: <a href=\"mailto:info@example.com\">Mystery@unimelb.edu.au</a></li>");
document.writeln("                    <li>Address: The University of Melbourne</li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\"clearfix\"> </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"header-bottom\">");
document.writeln("            <div class=\"container\">");
document.writeln("                <div class=\"col-md-3 logo-w3l\">");
document.writeln("                    <h1><a class=\"navbar-brand\" href=\"home.html\"><span>M</span>emories</a></h1>");
document.writeln("                </div>");
document.writeln("                <div class=\"col-md-9 navi-w3l\">");
document.writeln("                    <nav class=\"navbar navbar-default\">");
document.writeln("                        <div class=\"container-fluid\">");
document.writeln("                            <div class=\"navbar-header\">");
document.writeln("                                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">");
document.writeln("                                    <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                    <span class=\"icon-bar\"></span>");
document.writeln("                                </button>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.writeln("                                <nav class=\"menu menu--francisco\">");
document.writeln("                                    <ul class=\"nav navbar-nav menu__list\">");
document.writeln("                                        <li class=\"menu__item menu__item--current\"><a href=\"home\" class=\"menu__link\"><span class=\"menu__helper\">Home</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"artifacts\" class=\"menu__link scroll\"><span class=\"menu__helper\">Artifacts</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"family\" class=\"menu__link scroll\"><span class=\"menu__helper\">Family</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"account\" class=\"menu__link scroll\"><span class=\"menu__helper\">My Account</span></a></li>");
document.writeln("                                        <li class=\"menu__item\"><a href=\"upload\" class=\"menu__link scroll\"><span class=\"menu__helper\">Upload</span></a></li>");
document.writeln("                                    </ul>");
document.writeln("                                </nav>");
document.writeln("                                <div class=\"clearfix\"></div>");
document.writeln("                            </div><!-- /.navbar-collapse -->");
document.writeln("                        </div>");
document.writeln("                    </nav>");
document.writeln("                </div>");
document.writeln("                <div class=\"clearfix\"></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>");
document.writeln("<script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js\"></script>");
document.writeln("</body>");
document.writeln("</html>");